### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [abe33/atom-bezier-curve-editor#10]
Atom will no longer load this package after June 1st without changes. There is one deprecation on the latest version (`0.7.0`) of this package:

1. Call ::getActiveTextEditor instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by abe33** [comment]
Thanks for the reminder, I had missed this one.
